name: uni_links_example
version: 1.0.0+1
publish_to: none
description: Demonstrates how to use the uni_links plugin.
environment: 
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=2.0.1 <3.0.0'
dependencies: 
  cupertino_icons: ^1.0.5
  flutter: 
    sdk: flutter
  uni_links2: 
    path: ../
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
