name: uni_links_web2
version: 0.1.0+2
homepage: https://github.com/ericmartineau/uni_links/tree/master/uni_links_web
description: A web implementation of the Uni Links platform interface.
environment: 
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=2.0.1 <3.0.0'
dependencies: 
  uni_links2_platform_interface: ^1.0.0+2
  flutter: 
    sdk: flutter
  flutter_web_plugins: 
    sdk: flutter
dev_dependencies: 
  pedantic: ^1.11.0
  flutter_test: 
    sdk: flutter
flutter: 
  plugin: 
    platforms: 
      web: 
        pluginClass: UniLinksPlugin
        fileName: uni_links_web.dart
