name: uni_links2_platform_interface
version: 1.0.0+2
homepage: https://github.com/ericmartineau/uni_links/tree/master/uni_links_platform_interface
description: The platform interface for the uni_links plugin.
environment: 
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=2.0.1 <3.0.0'
dependencies: 
  plugin_platform_interface: ^2.1.2
  flutter: 
    sdk: flutter
dev_dependencies: 
  pedantic: ^1.11.1
  flutter_test: 
    sdk: flutter
